/**
 * The 20 Premier League clubs — the reference data behind every ClubBadge, club
 * tab and club picker in the app.
 *
 * `primaryColor` is the club's well-known kit colour, used only to tint the
 * generated placeholder crest. Real crests are trademarked (§13); `public/crests/`
 * holds neutral initials-on-colour SVGs generated by `scripts/generate-crests.mjs`.
 * Swapping in licensed artwork later is a one-file change here.
 */

export type ClubId =
  | 'arsenal'
  | 'aston-villa'
  | 'bournemouth'
  | 'brentford'
  | 'brighton'
  | 'chelsea'
  | 'crystal-palace'
  | 'everton'
  | 'fulham'
  | 'ipswich'
  | 'leicester'
  | 'liverpool'
  | 'man-city'
  | 'man-utd'
  | 'newcastle'
  | 'nottingham-forest'
  | 'southampton'
  | 'tottenham'
  | 'west-ham'
  | 'wolves'

export interface Club {
  id: ClubId
  /** Full name, rendered verbatim — never snake_cased (§3.3b guardrail 1). */
  name: string
  /** Short form for dense table cells and club tabs. */
  short: string
  stadium: string
  city: string
  primaryColor: string
  crest: string
}

function club(
  id: ClubId,
  name: string,
  short: string,
  stadium: string,
  city: string,
  primaryColor: string,
): Club {
  return { id, name, short, stadium, city, primaryColor, crest: `/crests/${id}.svg` }
}

export const CLUBS: Club[] = [
  club('arsenal', 'Arsenal', 'Arsenal', 'Emirates Stadium', 'London', '#EF0107'),
  club('aston-villa', 'Aston Villa', 'Villa', 'Villa Park', 'Birmingham', '#670E36'),
  club(
    'bournemouth',
    'AFC Bournemouth',
    'Bournemouth',
    'Vitality Stadium',
    'Bournemouth',
    '#DA291C',
  ),
  club('brentford', 'Brentford', 'Brentford', 'Gtech Community Stadium', 'London', '#E30613'),
  club('brighton', 'Brighton & Hove Albion', 'Brighton', 'Amex Stadium', 'Brighton', '#0057B8'),
  club('chelsea', 'Chelsea', 'Chelsea', 'Stamford Bridge', 'London', '#034694'),
  club('crystal-palace', 'Crystal Palace', 'Palace', 'Selhurst Park', 'London', '#1B458F'),
  club('everton', 'Everton', 'Everton', 'Hill Dickinson Stadium', 'Liverpool', '#003399'),
  club('fulham', 'Fulham', 'Fulham', 'Craven Cottage', 'London', '#1B1B1B'),
  club('ipswich', 'Ipswich Town', 'Ipswich', 'Portman Road', 'Ipswich', '#3A64A3'),
  club('leicester', 'Leicester City', 'Leicester', 'King Power Stadium', 'Leicester', '#003090'),
  club('liverpool', 'Liverpool', 'Liverpool', 'Anfield', 'Liverpool', '#C8102E'),
  club('man-city', 'Manchester City', 'Man City', 'Etihad Stadium', 'Manchester', '#6CABDD'),
  club('man-utd', 'Manchester United', 'Man Utd', 'Old Trafford', 'Manchester', '#DA291C'),
  club('newcastle', 'Newcastle United', 'Newcastle', "St James' Park", 'Newcastle', '#241F20'),
  club(
    'nottingham-forest',
    'Nottingham Forest',
    'Forest',
    'The City Ground',
    'Nottingham',
    '#DD0000',
  ),
  club('southampton', 'Southampton', 'Southampton', "St Mary's Stadium", 'Southampton', '#D71920'),
  club('tottenham', 'Tottenham Hotspur', 'Spurs', 'Tottenham Hotspur Stadium', 'London', '#132257'),
  club('west-ham', 'West Ham United', 'West Ham', 'London Stadium', 'London', '#7A263A'),
  club(
    'wolves',
    'Wolverhampton Wanderers',
    'Wolves',
    'Molineux Stadium',
    'Wolverhampton',
    '#FDB913',
  ),
]

const BY_ID = new Map(CLUBS.map((c) => [c.id, c]))

export function getClub(id: ClubId): Club {
  const found = BY_ID.get(id)
  if (!found) throw new Error(`Unknown club: ${id}`)
  return found
}

/** Two-letter mark for the generated crest and for avatar fallbacks. */
export function clubInitials(club: Club): string {
  const words = club.short.split(/\s+/)
  if (words.length > 1) return (words[0]![0]! + words[1]![0]!).toUpperCase()
  return club.short.slice(0, 2).toUpperCase()
}
