import type { Account, Fixture, Ticket } from '@/lib/types'
import type { LocaleSettings } from '@/lib/format/locale'
import { formatDateTime } from '@/lib/format/date'
import { formatMoney } from '@/lib/format/money'
import { getClub } from '@/lib/registries/clubs'

/**
 * `Actions -> Download PDF` (§8.5).
 *
 * The club's barcoded PDF comes from the club, and Fetch.io has no endpoint that
 * fetches it. What an operator actually reaches for this button for is the other
 * thing: a sheet of exactly which seats they are holding, to print, to hand over, or
 * to check against a buyer's message. That needs no backend at all, so it is built
 * here rather than disabled — and the footer says plainly which of the two documents
 * this is, so nobody takes it to a turnstile.
 *
 * The PDF is written by hand: a dependency for one page of Courier would be a
 * megabyte of parser for something the format expresses in ninety lines. Everything
 * is Latin-1 by construction (see `ascii`), so a character index is a byte offset and
 * the cross-reference table can be built by counting the strings.
 */

const PAGE_WIDTH = 595
const PAGE_HEIGHT = 842
const MARGIN = 48
const LINE = 14
const ROWS_PER_PAGE = 44

export interface SeatSheet {
  fixture: Fixture
  tickets: Ticket[]
  accounts: Map<string, Account>
  settings: LocaleSettings
}

/** `arsenal-v-chelsea-seats-4.pdf` */
export function seatSheetFilename({ fixture, tickets }: Pick<SeatSheet, 'fixture' | 'tickets'>) {
  const home = getClub(fixture.homeClub).short.toLowerCase().replace(/\s+/g, '-')
  const away = getClub(fixture.awayClub).short.toLowerCase().replace(/\s+/g, '-')
  return `${home}-v-${away}-seats-${tickets.length}.pdf`
}

export function buildSeatSheet(input: SeatSheet): Blob {
  const { fixture, tickets, accounts, settings } = input
  const home = getClub(fixture.homeClub)
  const away = getClub(fixture.awayClub)

  const title = `${home.name} v ${away.name}`
  const subtitle = `${formatDateTime(fixture.kickoff, settings)} - ${fixture.venue.name}, ${fixture.venue.city}`

  const header = row('BLOCK', 'ROW', 'SEAT', 'PRICE', 'FACE', 'ACCOUNT', 'STATUS')
  const body = tickets.map((ticket) =>
    row(
      ticket.block,
      ticket.row,
      ticket.seat,
      money(ticket.price, ticket.currency, settings),
      money(ticket.faceValue, ticket.currency, settings),
      accounts.get(ticket.accountId)?.email ?? ticket.accountId,
      ticket.status,
    ),
  )

  const footer = `Generated by Fetch.io on ${formatDateTime(new Date(), settings)}. Seat summary only - this is not the club's ticket.`

  const pages = chunk(body, ROWS_PER_PAGE)
  if (pages.length === 0) pages.push([])

  return new Blob([render({ title, subtitle, header, pages, footer })], {
    type: 'application/pdf',
  })
}

/* ------------------------------------------------------------- the PDF */

interface Sheet {
  title: string
  subtitle: string
  header: string
  pages: string[][]
  footer: string
}

function render(sheet: Sheet): ArrayBuffer {
  const pageCount = sheet.pages.length

  // 1 catalog, 2 pages, 3 display font, 4 mono, 5 mono bold, then two objects per page.
  const firstPageObject = 6
  const pageIds = sheet.pages.map((_, i) => firstPageObject + i * 2)

  const objects: string[] = [
    `<< /Type /Catalog /Pages 2 0 R >>`,
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageCount} >>`,
    `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>`,
    `<< /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >>`,
    `<< /Type /Font /Subtype /Type1 /BaseFont /Courier-Bold /Encoding /WinAnsiEncoding >>`,
  ]

  sheet.pages.forEach((rows, index) => {
    const contentId = pageIds[index]! + 1
    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] ` +
        `/Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R >> >> /Contents ${contentId} 0 R >>`,
    )
    const stream = content(sheet, rows, index, pageCount)
    objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)
  })

  // Assemble, recording where each object starts. Latin-1 by construction, so a
  // character count IS a byte count and the xref offsets below are exact.
  let out = '%PDF-1.4\n'
  const offsets: number[] = []

  objects.forEach((body, index) => {
    offsets.push(out.length)
    out += `${index + 1} 0 obj\n${body}\nendobj\n`
  })

  const startxref = out.length
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const offset of offsets) out += `${String(offset).padStart(10, '0')} 00000 n \n`
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${startxref}\n%%EOF\n`

  const buffer = new ArrayBuffer(out.length)
  const bytes = new Uint8Array(buffer)
  for (let i = 0; i < out.length; i++) bytes[i] = out.charCodeAt(i) & 0xff
  return buffer
}

function content(sheet: Sheet, rows: string[], index: number, pageCount: number): string {
  const lines: string[] = []
  let y = PAGE_HEIGHT - MARGIN

  const write = (font: 'F1' | 'F2' | 'F3', size: number, text: string) => {
    lines.push(`BT /${font} ${size} Tf ${MARGIN} ${y} Td (${escape(text)}) Tj ET`)
  }

  if (index === 0) {
    write('F1', 16, sheet.title)
    y -= 20
    write('F2', 9, sheet.subtitle)
    y -= 24
  } else {
    write('F1', 11, `${sheet.title} (continued)`)
    y -= 22
  }

  // Courier-Bold, not Helvetica-Bold: the header has to line up with the Courier rows
  // under it, and a proportional face cannot.
  write('F3', 8, sheet.header)
  y -= 4
  lines.push(`${MARGIN} ${y} m ${PAGE_WIDTH - MARGIN} ${y} l 0.75 w 0.6 0.6 0.6 RG S`)
  y -= LINE

  for (const row of rows) {
    write('F2', 8, row)
    y -= LINE
  }

  const footerY = MARGIN - 12
  lines.push(`BT /F2 7 Tf ${MARGIN} ${footerY} Td (${escape(sheet.footer)}) Tj ET`)
  lines.push(
    `BT /F2 7 Tf ${PAGE_WIDTH - MARGIN - 40} ${footerY} Td (${escape(`${index + 1} / ${pageCount}`)}) Tj ET`,
  )

  return lines.join('\n')
}

/* ----------------------------------------------------------- formatting */

/**
 * Fixed-width columns, sized so the whole row fits inside the margins at Courier 8pt
 * (0.6em per character, so 96 characters is 460 of the 499 points available).
 */
const COLUMN_WIDTHS = [22, 4, 5, 11, 11, 26, 11]

function row(...cells: string[]): string {
  return cells.map((cell, i) => pad(ascii(cell), COLUMN_WIDTHS[i]!)).join(' ')
}

function pad(value: string, width: number): string {
  const clipped = value.length > width ? `${value.slice(0, width - 3)}...` : value
  return clipped.padEnd(width)
}

function money(amount: number, currency: Ticket['currency'], settings: LocaleSettings): string {
  // The currency CODE, not the symbol: the sheet is printed, and a symbol the base
  // font cannot draw is worse than three letters it always can. The number itself
  // still goes through the one formatter, so it groups the way the rest of the app does.
  const formatted = formatMoney({ amount, currency }, settings).replace(/[^\d.,-]/g, '')
  return `${currency} ${formatted}`
}

/**
 * The PDF fonts are single-byte, so anything above Latin-1 has to become something
 * that can be drawn. Losing an en dash is fine; drawing a random glyph in a seat
 * number is not.
 */
function ascii(value: string): string {
  return value
    .replace(/[‒-―−]/g, '-')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/…/g, '...')
    .replace(/[^\x20-\x7E]/g, '')
}

/** `(`, `)` and `\` end or escape a PDF string literal, so they are escaped first. */
function escape(value: string): string {
  return ascii(value).replace(/([\\()])/g, '\\$1')
}

function chunk<T>(values: T[], size: number): T[][] {
  const out: T[][] = []
  for (let i = 0; i < values.length; i += size) out.push(values.slice(i, i + size))
  return out
}

/* ------------------------------------------------------------ download */

/** Hands the browser a file. Revoked on the next tick so the object URL cannot leak. */
export function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  setTimeout(() => URL.revokeObjectURL(url), 0)
}
